// fastapi_agent/react-components.tsx
import React, { useState, useRef, useCallback } from 'react';
import { 
  FastAPIAgentClient, 
  ChatRequest, 
  ChatResponse, 
  VoiceRequest, 
  VoiceResponse,
  ProcessRequest,
  ProcessResponse,
  CheckAvailabilityRequest,
  CheckAvailabilityResponse,
  CreateOrderRequest,
  CreateOrderResponse,
  blobToBase64,
  base64ToBlob
} from './types';

// Chat Component
interface ChatComponentProps {
  userId: number;
  baseUrl?: string;
  onMessage?: (message: string) => void;
}

export const ChatComponent: React.FC<ChatComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  onMessage 
}) => {
  const [messages, setMessages] = useState<Array<{ role: 'user' | 'assistant'; content: string }>>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState<number | null>(null);
  
  const client = new FastAPIAgentClient(baseUrl);

  const sendMessage = useCallback(async (message: string) => {
    if (!message.trim()) return;

    setIsLoading(true);
    
    // Add user message
    const newMessages = [...messages, { role: 'user' as const, content: message }];
    setMessages(newMessages);

    try {
      const request: ChatRequest = {
        message,
        session_id: sessionId || undefined,
        context: { user_id: userId }
      };

      const response: ChatResponse = await client.chat(request);
      
      // Add assistant response
      setMessages([...newMessages, { role: 'assistant', content: response.message }]);
      setSessionId(response.session_id);
      
      if (onMessage) {
        onMessage(response.message);
      }
    } catch (error) {
      console.error('Chat error:', error);
      setMessages([...newMessages, { 
        role: 'assistant', 
        content: 'عذراً، حدث خطأ في المعالجة. حاول مرة أخرى.' 
      }]);
    } finally {
      setIsLoading(false);
    }
  }, [messages, sessionId, userId, client, onMessage]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    sendMessage(inputMessage);
    setInputMessage('');
  };

  return (
    <div className="chat-container">
      <div className="messages">
        {messages.map((message, index) => (
          <div key={index} className={`message ${message.role}`}>
            <div className="message-content">
              {message.content}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="message assistant">
            <div className="message-content">
              <div className="typing-indicator">...</div>
            </div>
          </div>
        )}
      </div>
      
      <form onSubmit={handleSubmit} className="message-form">
        <input
          type="text"
          value={inputMessage}
          onChange={(e) => setInputMessage(e.target.value)}
          placeholder="اكتب رسالتك هنا..."
          disabled={isLoading}
          className="message-input"
        />
        <button type="submit" disabled={isLoading || !inputMessage.trim()}>
          إرسال
        </button>
      </form>
    </div>
  );
};

// Voice Component
interface VoiceComponentProps {
  userId: number;
  baseUrl?: string;
  onTranscription?: (text: string) => void;
  onResponse?: (response: string) => void;
}

export const VoiceComponent: React.FC<VoiceComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  onTranscription,
  onResponse
}) => {
  const [isRecording, setIsRecording] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [sessionId, setSessionId] = useState<number | null>(null);
  
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  
  const client = new FastAPIAgentClient(baseUrl);

  const startRecording = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;
      audioChunksRef.current = [];

      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          audioChunksRef.current.push(event.data);
        }
      };

      mediaRecorder.onstop = async () => {
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/wav' });
        await processVoiceMessage(audioBlob);
        stream.getTracks().forEach(track => track.stop());
      };

      mediaRecorder.start();
      setIsRecording(true);
    } catch (error) {
      console.error('Error starting recording:', error);
    }
  }, []);

  const stopRecording = useCallback(() => {
    if (mediaRecorderRef.current && isRecording) {
      mediaRecorderRef.current.stop();
      setIsRecording(false);
    }
  }, [isRecording]);

  const processVoiceMessage = useCallback(async (audioBlob: Blob) => {
    setIsProcessing(true);
    
    try {
      const base64Audio = await blobToBase64(audioBlob);
      
      const request: VoiceRequest = {
        audio_base64: base64Audio,
        session_id: sessionId || undefined,
        context: { user_id: userId }
      };

      const response: VoiceResponse = await client.voice(request);
      
      setSessionId(response.session_id);
      
      if (onTranscription) {
        onTranscription(response.transcription);
      }
      
      if (onResponse) {
        onResponse(response.text);
      }

      // Play response audio
      const responseBlob = base64ToBlob(response.audio_base64);
      const audioUrl = URL.createObjectURL(responseBlob);
      const audio = new Audio(audioUrl);
      await audio.play();
      
    } catch (error) {
      console.error('Voice processing error:', error);
    } finally {
      setIsProcessing(false);
    }
  }, [sessionId, userId, client, onTranscription, onResponse]);

  return (
    <div className="voice-component">
      <button
        onMouseDown={startRecording}
        onMouseUp={stopRecording}
        onTouchStart={startRecording}
        onTouchEnd={stopRecording}
        disabled={isProcessing}
        className={`voice-button ${isRecording ? 'recording' : ''}`}
      >
        {isProcessing ? 'معالجة...' : isRecording ? 'تحدث الآن' : 'اضغط للتحدث'}
      </button>
    </div>
  );
};

// Smart Processing Component
interface SmartProcessingComponentProps {
  userId: number;
  baseUrl?: string;
  onResponse?: (response: string, actions: any[]) => void;
}

export const SmartProcessingComponent: React.FC<SmartProcessingComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  onResponse
}) => {
  const [query, setQuery] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);
  
  const client = new FastAPIAgentClient(baseUrl);

  const processQuery = useCallback(async (text: string) => {
    if (!text.trim()) return;

    setIsProcessing(true);
    
    try {
      const request: ProcessRequest = {
        query: text,
        session_id: sessionId || undefined,
        context: { user_id: userId }
      };

      const response: ProcessResponse = await client.process(request);
      
      setSessionId(response.session_id || null);
      
      if (onResponse) {
        onResponse(response.response, response.actions);
      }
    } catch (error) {
      console.error('Processing error:', error);
    } finally {
      setIsProcessing(false);
    }
  }, [sessionId, userId, client, onResponse]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    processQuery(query);
    setQuery('');
  };

  return (
    <div className="smart-processing">
      <form onSubmit={handleSubmit} className="query-form">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="اكتب طلبك هنا (مثال: عايز 10 علب باراسيتامول)..."
          disabled={isProcessing}
          className="query-input"
        />
        <button type="submit" disabled={isProcessing || !query.trim()}>
          {isProcessing ? 'معالجة...' : 'معالجة ذكية'}
        </button>
      </form>
    </div>
  );
};

// Medicine Search Component
interface MedicineSearchComponentProps {
  userId: number;
  baseUrl?: string;
  onResults?: (results: CheckAvailabilityResponse) => void;
}

export const MedicineSearchComponent: React.FC<MedicineSearchComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  onResults
}) => {
  const [medicineName, setMedicineName] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [results, setResults] = useState<CheckAvailabilityResponse | null>(null);
  
  const client = new FastAPIAgentClient(baseUrl);

  const searchMedicine = useCallback(async (name: string) => {
    if (!name.trim()) return;

    setIsSearching(true);
    
    try {
      const request: CheckAvailabilityRequest = {
        medicine_name: name,
        user_id: userId
      };

      const response: CheckAvailabilityResponse = await client.checkAvailability(request);
      setResults(response);
      
      if (onResults) {
        onResults(response);
      }
    } catch (error) {
      console.error('Search error:', error);
    } finally {
      setIsSearching(false);
    }
  }, [userId, client, onResults]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    searchMedicine(medicineName);
  };

  return (
    <div className="medicine-search">
      <form onSubmit={handleSubmit} className="search-form">
        <input
          type="text"
          value={medicineName}
          onChange={(e) => setMedicineName(e.target.value)}
          placeholder="ابحث عن دواء..."
          disabled={isSearching}
          className="search-input"
        />
        <button type="submit" disabled={isSearching || !medicineName.trim()}>
          {isSearching ? 'بحث...' : 'بحث'}
        </button>
      </form>
      
      {results && (
        <div className="search-results">
          <h3>نتائج البحث:</h3>
          {results.available ? (
            <div className="available-medicines">
              {results.offers.map((offer, index) => (
                <div key={index} className="medicine-card">
                  <h4>{offer.name}</h4>
                  <p>السعر الأصلي: {offer.original_price} جنيه</p>
                  <p>الخصم: {offer.discount_percentage}%</p>
                  <p>متوفر: {offer.available ? 'نعم' : 'لا'}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="no-results">{results.message}</p>
          )}
        </div>
      )}
    </div>
  );
};

// Order Creation Component
interface OrderCreationComponentProps {
  userId: number;
  baseUrl?: string;
  onOrderCreated?: (order: CreateOrderResponse) => void;
}

export const OrderCreationComponent: React.FC<OrderCreationComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  onOrderCreated
}) => {
  const [medicineName, setMedicineName] = useState('');
  const [quantity, setQuantity] = useState(1);
  const [isCreating, setIsCreating] = useState(false);
  
  const client = new FastAPIAgentClient(baseUrl);

  const createOrder = useCallback(async (name: string, qty: number) => {
    if (!name.trim() || qty <= 0) return;

    setIsCreating(true);
    
    try {
      const request: CreateOrderRequest = {
        medicine_name: name,
        quantity: qty,
        user_id: userId
      };

      const response: CreateOrderResponse = await client.createOrder(request);
      
      if (onOrderCreated) {
        onOrderCreated(response);
      }
    } catch (error) {
      console.error('Order creation error:', error);
    } finally {
      setIsCreating(false);
    }
  }, [userId, client, onOrderCreated]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    createOrder(medicineName, quantity);
  };

  return (
    <div className="order-creation">
      <form onSubmit={handleSubmit} className="order-form">
        <input
          type="text"
          value={medicineName}
          onChange={(e) => setMedicineName(e.target.value)}
          placeholder="اسم الدواء"
          disabled={isCreating}
          className="medicine-input"
        />
        <input
          type="number"
          value={quantity}
          onChange={(e) => setQuantity(parseInt(e.target.value) || 1)}
          min="1"
          disabled={isCreating}
          className="quantity-input"
        />
        <button type="submit" disabled={isCreating || !medicineName.trim()}>
          {isCreating ? 'إنشاء...' : 'إنشاء طلب'}
        </button>
      </form>
    </div>
  );
};

// Main AI Agent Component
interface AIAgentComponentProps {
  userId: number;
  baseUrl?: string;
  mode?: 'chat' | 'voice' | 'smart' | 'search' | 'order';
}

export const AIAgentComponent: React.FC<AIAgentComponentProps> = ({ 
  userId, 
  baseUrl = 'http://localhost:8001',
  mode = 'chat'
}) => {
  const [currentMode, setCurrentMode] = useState(mode);

  const renderComponent = () => {
    switch (currentMode) {
      case 'chat':
        return <ChatComponent userId={userId} baseUrl={baseUrl} />;
      case 'voice':
        return <VoiceComponent userId={userId} baseUrl={baseUrl} />;
      case 'smart':
        return <SmartProcessingComponent userId={userId} baseUrl={baseUrl} />;
      case 'search':
        return <MedicineSearchComponent userId={userId} baseUrl={baseUrl} />;
      case 'order':
        return <OrderCreationComponent userId={userId} baseUrl={baseUrl} />;
      default:
        return <ChatComponent userId={userId} baseUrl={baseUrl} />;
    }
  };

  return (
    <div className="ai-agent-component">
      <div className="mode-selector">
        <button 
          className={currentMode === 'chat' ? 'active' : ''}
          onClick={() => setCurrentMode('chat')}
        >
          محادثة
        </button>
        <button 
          className={currentMode === 'voice' ? 'active' : ''}
          onClick={() => setCurrentMode('voice')}
        >
          صوت
        </button>
        <button 
          className={currentMode === 'smart' ? 'active' : ''}
          onClick={() => setCurrentMode('smart')}
        >
          معالجة ذكية
        </button>
        <button 
          className={currentMode === 'search' ? 'active' : ''}
          onClick={() => setCurrentMode('search')}
        >
          بحث
        </button>
        <button 
          className={currentMode === 'order' ? 'active' : ''}
          onClick={() => setCurrentMode('order')}
        >
          طلب
        </button>
      </div>
      
      <div className="component-container">
        {renderComponent()}
      </div>
    </div>
  );
};

// fastapi_agent/vue-components.vue
<template>
  <!-- Chat Component -->
  <div class="chat-component" v-if="mode === 'chat'">
    <div class="messages" ref="messagesContainer">
      <div 
        v-for="(message, index) in messages" 
        :key="index" 
        :class="['message', message.role]"
      >
        <div class="message-content">
          {{ message.content }}
        </div>
      </div>
      <div v-if="isLoading" class="message assistant">
        <div class="message-content">
          <div class="typing-indicator">...</div>
        </div>
      </div>
    </div>
    
    <form @submit.prevent="sendMessage" class="message-form">
      <input
        v-model="inputMessage"
        type="text"
        placeholder="اكتب رسالتك هنا..."
        :disabled="isLoading"
        class="message-input"
      />
      <button type="submit" :disabled="isLoading || !inputMessage.trim()">
        إرسال
      </button>
    </form>
  </div>

  <!-- Voice Component -->
  <div class="voice-component" v-else-if="mode === 'voice'">
    <button
      @mousedown="startRecording"
      @mouseup="stopRecording"
      @touchstart="startRecording"
      @touchend="stopRecording"
      :disabled="isProcessing"
      :class="['voice-button', { recording: isRecording }]"
    >
      {{ isProcessing ? 'معالجة...' : isRecording ? 'تحدث الآن' : 'اضغط للتحدث' }}
    </button>
  </div>

  <!-- Smart Processing Component -->
  <div class="smart-processing" v-else-if="mode === 'smart'">
    <form @submit.prevent="processQuery" class="query-form">
      <input
        v-model="query"
        type="text"
        placeholder="اكتب طلبك هنا (مثال: عايز 10 علب باراسيتامول)..."
        :disabled="isProcessing"
        class="query-input"
      />
      <button type="submit" :disabled="isProcessing || !query.trim()">
        {{ isProcessing ? 'معالجة...' : 'معالجة ذكية' }}
      </button>
    </form>
  </div>

  <!-- Medicine Search Component -->
  <div class="medicine-search" v-else-if="mode === 'search'">
    <form @submit.prevent="searchMedicine" class="search-form">
      <input
        v-model="medicineName"
        type="text"
        placeholder="ابحث عن دواء..."
        :disabled="isSearching"
        class="search-input"
      />
      <button type="submit" :disabled="isSearching || !medicineName.trim()">
        {{ isSearching ? 'بحث...' : 'بحث' }}
      </button>
    </form>
    
    <div v-if="searchResults" class="search-results">
      <h3>نتائج البحث:</h3>
      <div v-if="searchResults.available" class="available-medicines">
        <div 
          v-for="(offer, index) in searchResults.offers" 
          :key="index" 
          class="medicine-card"
        >
          <h4>{{ offer.name }}</h4>
          <p>السعر الأصلي: {{ offer.original_price }} جنيه</p>
          <p>الخصم: {{ offer.discount_percentage }}%</p>
          <p>متوفر: {{ offer.available ? 'نعم' : 'لا' }}</p>
        </div>
      </div>
      <p v-else class="no-results">{{ searchResults.message }}</p>
    </div>
  </div>

  <!-- Order Creation Component -->
  <div class="order-creation" v-else-if="mode === 'order'">
    <form @submit.prevent="createOrder" class="order-form">
      <input
        v-model="orderMedicineName"
        type="text"
        placeholder="اسم الدواء"
        :disabled="isCreating"
        class="medicine-input"
      />
      <input
        v-model.number="orderQuantity"
        type="number"
        min="1"
        :disabled="isCreating"
        class="quantity-input"
      />
      <button type="submit" :disabled="isCreating || !orderMedicineName.trim()">
        {{ isCreating ? 'إنشاء...' : 'إنشاء طلب' }}
      </button>
    </form>
  </div>

  <!-- Mode Selector -->
  <div class="mode-selector">
    <button 
      v-for="modeOption in modes" 
      :key="modeOption.value"
      :class="{ active: mode === modeOption.value }"
      @click="setMode(modeOption.value)"
    >
      {{ modeOption.label }}
    </button>
  </div>
</template>

<script>
import { FastAPIAgentClient, blobToBase64, base64ToBlob } from './types';

export default {
  name: 'FastAPIAgent',
  props: {
    userId: {
      type: Number,
      required: true
    },
    baseUrl: {
      type: String,
      default: 'http://localhost:8001'
    },
    initialMode: {
      type: String,
      default: 'chat'
    }
  },
  data() {
    return {
      mode: this.initialMode,
      modes: [
        { value: 'chat', label: 'محادثة' },
        { value: 'voice', label: 'صوت' },
        { value: 'smart', label: 'معالجة ذكية' },
        { value: 'search', label: 'بحث' },
        { value: 'order', label: 'طلب' }
      ],
      
      // Chat data
      messages: [],
      inputMessage: '',
      isLoading: false,
      sessionId: null,
      
      // Voice data
      isRecording: false,
      isProcessing: false,
      mediaRecorder: null,
      audioChunks: [],
      
      // Smart processing data
      query: '',
      
      // Search data
      medicineName: '',
      isSearching: false,
      searchResults: null,
      
      // Order data
      orderMedicineName: '',
      orderQuantity: 1,
      isCreating: false,
      
      // Client
      client: null
    };
  },
  created() {
    this.client = new FastAPIAgentClient(this.baseUrl);
  },
  methods: {
    setMode(mode) {
      this.mode = mode;
    },
    
    // Chat methods
    async sendMessage() {
      if (!this.inputMessage.trim()) return;
      
      this.isLoading = true;
      const userMessage = this.inputMessage;
      this.inputMessage = '';
      
      // Add user message
      this.messages.push({ role: 'user', content: userMessage });
      
      try {
        const response = await this.client.chat({
          message: userMessage,
          session_id: this.sessionId,
          context: { user_id: this.userId }
        });
        
        this.messages.push({ role: 'assistant', content: response.message });
        this.sessionId = response.session_id;
      } catch (error) {
        console.error('Chat error:', error);
        this.messages.push({ 
          role: 'assistant', 
          content: 'عذراً، حدث خطأ في المعالجة. حاول مرة أخرى.' 
        });
      } finally {
        this.isLoading = false;
        this.$nextTick(() => {
          this.scrollToBottom();
        });
      }
    },
    
    scrollToBottom() {
      const container = this.$refs.messagesContainer;
      if (container) {
        container.scrollTop = container.scrollHeight;
      }
    },
    
    // Voice methods
    async startRecording() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        this.mediaRecorder = new MediaRecorder(stream);
        this.audioChunks = [];
        
        this.mediaRecorder.ondataavailable = (event) => {
          if (event.data.size > 0) {
            this.audioChunks.push(event.data);
          }
        };
        
        this.mediaRecorder.onstop = async () => {
          const audioBlob = new Blob(this.audioChunks, { type: 'audio/wav' });
          await this.processVoiceMessage(audioBlob);
          stream.getTracks().forEach(track => track.stop());
        };
        
        this.mediaRecorder.start();
        this.isRecording = true;
      } catch (error) {
        console.error('Error starting recording:', error);
      }
    },
    
    stopRecording() {
      if (this.mediaRecorder && this.isRecording) {
        this.mediaRecorder.stop();
        this.isRecording = false;
      }
    },
    
    async processVoiceMessage(audioBlob) {
      this.isProcessing = true;
      
      try {
        const base64Audio = await blobToBase64(audioBlob);
        
        const response = await this.client.voice({
          audio_base64: base64Audio,
          session_id: this.sessionId,
          context: { user_id: this.userId }
        });
        
        this.sessionId = response.session_id;
        
        // Play response audio
        const responseBlob = base64ToBlob(response.audio_base64);
        const audioUrl = URL.createObjectURL(responseBlob);
        const audio = new Audio(audioUrl);
        await audio.play();
        
        this.$emit('voice-response', {
          text: response.text,
          transcription: response.transcription
        });
      } catch (error) {
        console.error('Voice processing error:', error);
      } finally {
        this.isProcessing = false;
      }
    },
    
    // Smart processing methods
    async processQuery() {
      if (!this.query.trim()) return;
      
      this.isProcessing = true;
      const query = this.query;
      this.query = '';
      
      try {
        const response = await this.client.process({
          query,
          session_id: this.sessionId,
          context: { user_id: this.userId }
        });
        
        this.sessionId = response.session_id;
        this.$emit('smart-response', {
          response: response.response,
          actions: response.actions
        });
      } catch (error) {
        console.error('Processing error:', error);
      } finally {
        this.isProcessing = false;
      }
    },
    
    // Search methods
    async searchMedicine() {
      if (!this.medicineName.trim()) return;
      
      this.isSearching = true;
      
      try {
        const response = await this.client.checkAvailability({
          medicine_name: this.medicineName,
          user_id: this.userId
        });
        
        this.searchResults = response;
        this.$emit('search-results', response);
      } catch (error) {
        console.error('Search error:', error);
      } finally {
        this.isSearching = false;
      }
    },
    
    // Order methods
    async createOrder() {
      if (!this.orderMedicineName.trim() || this.orderQuantity <= 0) return;
      
      this.isCreating = true;
      
      try {
        const response = await this.client.createOrder({
          medicine_name: this.orderMedicineName,
          quantity: this.orderQuantity,
          user_id: this.userId
        });
        
        this.$emit('order-created', response);
        
        // Reset form
        this.orderMedicineName = '';
        this.orderQuantity = 1;
      } catch (error) {
        console.error('Order creation error:', error);
      } finally {
        this.isCreating = false;
      }
    }
  }
};
</script>

<style scoped>
/* Import the main styles */
@import './styles.css';

/* Component-specific styles */
.mode-selector {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
  flex-wrap: wrap;
}

.mode-selector button {
  padding: 10px 20px;
  border: 2px solid #007bff;
  background: white;
  color: #007bff;
  border-radius: 25px;
  cursor: pointer;
  transition: all 0.3s ease;
  font-weight: 500;
}

.mode-selector button:hover {
  background: #007bff;
  color: white;
}

.mode-selector button.active {
  background: #007bff;
  color: white;
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .mode-selector {
    flex-direction: column;
  }
  
  .mode-selector button {
    width: 100%;
  }
}
</style>
